name: 03 - build node aplication
on: 
    push:
       branches: ["main"] 
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:   
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20        
    - run: npm install --save-dev @babel/core @babel/preset-env @babel/preset-react babel-jest @babel/plugin-transform-runtime
    - run: npm install
    - run: npm install --save-dev @testing-library/react-native @testing-library/jest-native
    - run: npm test 

