name: Build Android Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install Node dependencies
      run: npm install

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches/
          ~/.gradle/wrapper/
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Clean project
      run: ./gradlew clean
      working-directory: android
      env:
        JAVA_HOME: ${{ env.JAVA_HOME_17}}

    - name: Build with Gradle
      run: ./gradlew app:assembleRelease
      working-directory: android
      env:
        JAVA_HOME: ${{ env.JAVA_HOME_17}}

    - name: Save APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-release-apk
        path: android/app/build/outputs/apk/release/app-release.apk
